### PR TITLE
Captum Refactoring

### PR DESCRIPTION
**Pull request by nareshr8**
Refactoring of Code to make it as Interpretation than Callback

### CODE REVIEW

**Comment by nareshr8** [comment]
I have refactored the code. But I havent changed the Notebook name or `default_exp` as I am not exactly sure which one is appropriate. Kindly review and change them as appropriate. Let know if you find any other issue as well.

**Comment by sgugger** [comment]
There is no need to change the notebook name or module (ultimately it will be in a separate extension like tensorboard, wandb, neptune or medical since it adds a new dependency).

This is looking cleaner and better, thanks! two remarks:
- I think you misspelled gauss to guass
- Remember to commit cleaned notebooks in your PRs buy running `nbdev_install_git_hooks` in the repo after cloning it.

**Comment by nareshr8** [comment]
Have made the typo changes and ran `nbdev_install_git_hooks`

**Comment by sgugger** [comment]
Thanks!

**Pull request merged**
