### PR TITLE
Captum Insights for Image Classsification with IG and Deconvolution

### PR DESCRIPTION
**Pull request by nareshr8**
Captum Insights for IG and Deconvolution

### CODE REVIEW

**Comment by nareshr8** [comment]
Currently Integrated Gradients and Deconvolution option alone works.

**Comment by sgugger** [comment]
There is already a captum notebook, could you please integrate your work inside it?

**Comment by nareshr8** [comment]
Since Captum insights was a different functionality, I thought have creating a different callback. There is minimal common functionality between them. Are you suggesting to have a different callback inside the same notebook..

**Comment by sgugger** [comment]
Yes please, a different Callback in the same notebook (and then module).

**Pull request closed without merging**
