### PR TITLE
feat(gather_args): improve args collected

### PR DESCRIPTION
**Pull request by borisdayma**
This PR requires merging [fastcore PR 21](https://github.com/fastai/fastcore/pull/21) first.

Changes:
* `Learner.gather_args` -> add args from `WandbCallback._log_config`
* `WandbCallback` -> pull args from `Learner.gather_args`

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks a lot for the PR.
Could you patch the gather_args method at the end of the notebook, to avoid the `Learner` cell to be overcrowded?

**Comment by borisdayma** [comment]
Here is a notebook to play with: https://gist.github.com/borisdayma/396a01365f834acd7c04069c1053d1cb

I manually changed a few parameters (cbs, epochs, arch…) and this is the table we get: https://app.wandb.ai/borisd13/demo_/table?workspace=user-borisd13

There's a little issue with the "magic" function on the UI that shows most useful columns because it removes `GradientAccumulation` and `GradientAccumulation.n_acc` but I'm sure it can be fixed.

**Comment by borisdayma** [comment]
Don't forget that the fastcore PR should be merged first.

**Comment by sgugger** [comment]
I'll defer to you on what is best to be logged or not. Do you want to do it in this PR or a separate one? Otherwise this looks good to me and can be merged, thanks!

**Comment by borisdayma** [comment]
Ok let me remove it quickly

**Comment by borisdayma** [comment]
Ready to merge if you're good with it!

**Comment by sgugger** [comment]
Let's do this then. Thanks a lot for all your work!

**Comment by borisdayma** [comment]
I think it's going to be really cool!

I'm going to talk to the W&B guys about it as I think they can do a few things in the UI that will let us have a clean workflow.

I'll make a post during the week in the forums to discuss it.

**Pull request merged**
