### PR TITLE
Fix categorical issue

### PR DESCRIPTION
**Pull request by muellerzr**
This should fix it, let me know otherwise if you had a different idea

### CODE REVIEW

**Comment by sgugger** [comment]
No, this does not change the fact that categories are set on the whole dataframe instead of just the training part. Make sure all the notebook can run with your change, you should see the tests of Categorify fail.

**Comment by muellerzr** [comment]
Got it, my apologies. Let me look back at it real quick

**Comment by muellerzr** [comment]
Tests pass now :)

**Comment by sgugger** [comment]
I think you can put all the conts to float, no?

**Comment by muellerzr** [comment]
Yes, you are right. We wouldn't have the same issue there

**Comment by sgugger** [comment]
Thanks!

**Comment by muellerzr** [comment]
Thank you for helping me work through it :)

**Pull request merged**
