### PR TITLE
Expanding the Tabular documentation

### PR DESCRIPTION
**Pull request by muellerzr**
This is a little bit of documentation for tabular, as this has been a problem I notice people get confused on.

### CODE REVIEW

**Comment by muellerzr** [comment]
I'll also try to flesh out some work on the tabular documentation over the next few days, if you feel this would be better suited for a different notebook let me know!

**Comment by muellerzr** [comment]
@sgugger let me know if this is a good start on expanding some of the documentation? If so I'll continue :)

**Comment by sgugger** [comment]
This looks good to me.
Sidenote: I think `Categorify` and `NormalizeTab` are legacy and not used anywhere, so I'll probably remove them soon.

**Comment by muellerzr** [comment]
If I’m understanding correctly, instead we use the type dispatch call instead for them? (@Normalize, etc)

**Comment by sgugger** [comment]
Yes, we use Categorize and Normalize.

**Comment by muellerzr** [comment]
Got it, thanks!

**Pull request merged**
