### PR TITLE
PathLabeller

### PR DESCRIPTION
**Pull request by nareshr8**
Add PathLabeller as a labelling function

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR, but this duplicates the RegexLabeller. I don't understand what new functionality this is adding.

**Comment by nareshr8** [comment]
I had to get the label from grandparent. Getting Grandparent through Regex was hard for me. So I modified RegexLabeller a bit to accommodate the same and shared. If it can be achieved through RegexLabeller feel free to cancel the pull request.

**Comment by sgugger** [comment]
Let me check, but you should always be able to pass a list of function to `get_y` in the data block API (if that's not the case I will fix). So you should be able to say `get_y = [grand_parent, RegexLabeller(...)]` with grand_parent being a function that returns the grand parent name. I think this a bit more modular instead of having all the pieces in one big block.

I'm closing this PR and checking that the above works (and if it does not, will fix this morning :) )

**Comment by sgugger** [comment]
Just updated the example for the pets dataset in 50_datablock_examples to use a list in get_y, it works perfectly ;)

**Pull request closed without merging**
