### PR TITLE
Fix "None"

### PR DESCRIPTION
**Pull request by muellerzr**
Needed to be NoneType, not "None" for pandas warning

### CODE REVIEW

**Comment by muellerzr** [comment]
This *should* be the last mini-PR that I've discovered until I explore the `.setup()` (and if there's anything I can really even do there)

**Comment by muellerzr** [comment]
Don't merge it quite yet though, in case I do let's use this as the one PR :)

**Comment by muellerzr** [comment]
Okay, good to merge. I was actually going crazy and didn't realize that doing `df = df.append(df)` will essentially multiply your memory usage. Memory reduction looks much more sane now, and added overhead even with a 6.5gb file is only 8.1gb

**Comment by sgugger** [comment]
Thanks!

**Pull request merged**
