### PR TITLE
Fix 'Unhashable type L'

### PR DESCRIPTION
**Pull request by amaarora**

### CODE REVIEW

**Comment by amaarora** [comment]
On running `30_text.core`, I get an error "Unhashable type `L`"  at cell 50. 

To replicate: 
```
with tempfile.TemporaryDirectory() as tmp_d:
    path,df,csv_fname = _prepare_texts(Path(tmp_d))    
    #Tokenize as a dataframe
    out,cnt_b = tokenize_df(df, text_cols='text')
    test_eq(list(out.columns), ['label', 'text'])
    test_eq(out['label'].values, df['label'].values)
    test_eq(out['text'], [(outp/d/f'text{i}.txt').read().split(' ') for i in range(5) for d in ['a', 'b', 'c']])
    test_eq(cnt_a, cnt_b)
```

I get this error: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-111-f4a833a16426> in <module>()
      2     path,df,csv_fname = _prepare_texts(Path(tmp_d))
      3     #Tokenize as a dataframe
----> 4     out,cnt_b = tokenize_df(df, text_cols='text')
      5     test_eq(list(out.columns), ['label', 'text'])
      6     test_eq(out['label'].values, df['label'].values)

<ipython-input-106-ed34d0a60e45> in tokenize_df(df, text_cols, n_workers, rules, mark_fields, tok_func, res_col_name, **tok_kwargs)
      7     if mark_fields is None: mark_fields = len(text_cols)>1
      8     rules = L(ifnone(rules, defaults.text_proc_rules.copy()))
----> 9     texts = _join_texts(df[text_cols], mark_fields=mark_fields)
     10     outputs = L(parallel_tokenize(texts, tok_func, rules, n_workers=n_workers, **tok_kwargs)
     11                ).sorted().itemgot(1)

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2137             return self._getitem_multilevel(key)
   2138         else:
-> 2139             return self._getitem_column(key)
   2140 
   2141     def _getitem_column(self, key):

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in _getitem_column(self, key)
   2144         # get column
   2145         if self.columns.is_unique:
-> 2146             return self._get_item_cache(key)
   2147 
   2148         # duplicate columns & possible reduce dimensionality

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   1838         """Return the cached item, item represents a label indexer."""
   1839         cache = self._item_cache
-> 1840         res = cache.get(item)
   1841         if res is None:
   1842             values = self._data.get(item)

TypeError: unhashable type: 'L'
```

**Comment by sgugger** [comment]
I agree that should fix the problem, but I am unable to replicate. Are you sure you have the latest version of fastcore?

**Comment by amaarora** [comment]
Thanks @sgugger for the response, actually I just pulled the latest version of fastai2 repo and started running notebook `30_text.core.ipynb`. 

This error is still occurring if I run notebook `30_text.core` . I just ran all the cells of `30_text.core` and get this error at the cell with the following code: 

```
with tempfile.TemporaryDirectory() as tmp_d:
    path,df,csv_fname = _prepare_texts(Path(tmp_d))
    #Tokenize as folders
    tokenize_folder(path)
    outp = Path(tmp_d)/'tmp_tok'
    for d in ['a', 'b', 'c']: 
        p = outp/d
        for i in range(5):
            test_eq((p/f'text{i}.txt').read(), ' '.join([
                BOS, TK_MAJ, 'this', 'is', 'an', 'example', 'of', 'text', d, str(i) ]))
    cnt_a = (outp/fn_counter_pkl).load()
    test_eq(cnt_a['this'], 15)
    test_eq(cnt_a['a'], 5)
    test_eq(cnt_a['0'], 3)
    
    #Tokenize as files
    files = get_text_files(path)
    tokenize_files(files, path/'d')
    for i,f in enumerate(files): 
        test_eq((path/'d'/f'{i}.txt').read(), ' '.join([
                BOS, TK_MAJ, 'this', 'is', 'an', 'example', 'of', 'text', f.parent.name, f.name[4]]))
    
    #Tokenize as a dataframe
    out,cnt_b = tokenize_df(df, text_cols='text')
    test_eq(list(out.columns), ['label', 'text'])
    test_eq(out['label'].values, df['label'].values)
    test_eq(out['text'], [(outp/d/f'text{i}.txt').read().split(' ') for i in range(5) for d in ['a', 'b', 'c']])
    test_eq(cnt_a, cnt_b)
    
    #Tokenize as a csv 
    out_fname = Path(tmp_d)/'output.csv'
    tokenize_csv(csv_fname, text_cols='text', outname=out_fname)
    test_eq((out,cnt_b), load_tokenized_csv(out_fname))
```

This cell is cell number 50 for me under **Tokenize texts in a dataframe** markdown heading.

I have fastcore 0.1.10 version installed, but believe that this error is coming from the code within the `30_text.core` notebook itself where the `tokenize_df` function is defined. 

```
#export
def tokenize_df(df, text_cols, n_workers=defaults.cpus, rules=None, mark_fields=None,
                tok_func=SpacyTokenizer, res_col_name="text", **tok_kwargs):
    "Tokenize texts in `df[text_cols]` in parallel using `n_workers`"
    text_cols = L(df.columns[c] if isinstance(c, int) else c for c in L(text_cols))
    #mark_fields defaults to False if there is one column of texts, True if there are multiple
    if mark_fields is None: mark_fields = len(text_cols)>1
    rules = L(ifnone(rules, defaults.text_proc_rules.copy()))
    texts = _join_texts(df[text_cols], mark_fields=mark_fields)
    outputs = L(parallel_tokenize(texts, tok_func, rules, n_workers=n_workers, **tok_kwargs)
               ).sorted().itemgot(1)

    other_cols = df.columns[~df.columns.isin(text_cols)]
    res = df[other_cols].copy()
    res[res_col_name] = outputs
    return res,Counter(outputs.concat())
```

I believe just by just re running notebook 3`0_text.core`, you should be able to replicate the issue. Please let me if not and if I have made a mistake at my end :)

**Comment by sgugger** [comment]
Like I said, it runs fine for me. Do you have the master version of fastcore?

**Comment by amaarora** [comment]
`febe6caf4f7a411791e347bff5737a75eb15a188` 
This is what I get when I run `git rev-parse origin/master` on my fastcore repo

**Comment by sgugger** [comment]
Weird. I don't know why there is inconsistent behavior here. This doesn't do any harm in any case, so merging.

**Pull request merged**
