### PR TITLE
Add zebra finch2

### PR DESCRIPTION
**Pull request by radekosmulski**
Terribly sorry about the earlier PR for adding the `ZEBRA_FINCH` dataset. There were things that were missing - I add them in this PR.

### CODE REVIEW

**Comment by radekosmulski** [comment]
I am not sure how come this is failing, since running `nbdev_diff_nbs` produces no output (just a blank line) `nbdev_build_lib` doesn't change anything.

**Comment by radekosmulski** [comment]
after I updated `nbdev` I am now getting output from `nbdev_diff_nbs`... investigating further

**Comment by radekosmulski** [comment]
ok, there were some updates, pushed the new version generated with updated `nbdev`

**Comment by radekosmulski** [comment]
it worked 🙂

**Comment by sgugger** [comment]
Yes there have been a few fixes in nbdev :)
Thanks for fixing, I was wondering why there was no need for the checks to be added ;)

**Pull request merged**
