### PR TITLE
`BnFreeze` callback for fully frozen BatchNorm layers

### PR DESCRIPTION
**Pull request by rsomani95**
Replicate `BnFreeze` from v1 (https://docs.fast.ai/train.html#BnFreeze) with some additional documentation, examples and a test

### CODE REVIEW

**Comment by rsomani95** [comment]
The notebook is a bit verbose with outputs of the `models_equal` function. Let me know if you'd like that removed, or export `models_equal` into the fastai library, or of any other changes.

**Comment by sgugger** [comment]
Thanks for the PR. Don't forget the notebooks also become the documentation, so we can't have something that verbose. Just asserting it's false is enough for the test I believe.

**Comment by rsomani95** [comment]
That sounds fair. I'll make that change and commit.

**Comment by sgugger** [comment]
Thanks! I'll just add a #slow tag to your tests since they are a bit long.

**Pull request merged**
