### PR TITLE
fixes typo

### PR DESCRIPTION
**Pull request by lgvaz**
Self explanatory =)

### CODE REVIEW

**Comment by lgvaz** [comment]
Wait a bit before merging this one, there are some other fixes for this file on the way

**Comment by sgugger** [comment]
Ok, let me know when it's ready then.

**Comment by lgvaz** [comment]
Done!

Can I also make a request? When you have the time, can you add a quick example of how to use `predict` on the end of the nb? Thanks!

**Comment by sgugger** [comment]
Will do when I get to this tutorial (planning is [here](https://forums.fast.ai/t/documentation-help-needed/66289)).

**Pull request merged**
