### PR TITLE
fix show batch on RegressionBlock

### PR DESCRIPTION
**Pull request by tcapelle**
Add basic TitledFloat to RegressionSetup to be able to show batch

### CODE REVIEW

**Comment by sgugger** [comment]
Be careful, you have more changes committed than just this add. It should be in a separate PR.

**Comment by tcapelle** [comment]
<p>crap, why It did that, I am preparing a new PR for that.</p>

**Comment by tcapelle** [comment]
Can you reject the last commit?

**Comment by sgugger** [comment]
I can't remove a commit from the web interface. Can you just open a new PR with the change? It's tiny so shouldn't be too much work.

**Comment by tcapelle** [comment]
How do I do that ?

**Pull request closed without merging**
