### PR TITLE
Distrib training for tabular data!

### PR DESCRIPTION
**Pull request by philtrade**
`DistributedDL.create_item()`: Only return idx here, let `TabDataLoader.create_batch()` do its job using `iloc`.
`train_tabular.py`: Test driver  for training url.ADULT_SAMPLES from cmdline, in single or multi-GPU mode.  Derived from `train_imagenette.py`.

`torch_core.distrib_barrier()`: Check against uninitialized distrib environment b4 entering synchronization barrier.

### CODE REVIEW

**Comment by philtrade** [comment]
I'm a bit lost here, as to the `nbdev_diff_nbs` error?

I edited the notebook, ran `nbdev_build_lib`, ran test, then check in both the notebook and the .py files as usual.  The changes are simple one-liners.  Also added a new file under nbs/examples/.

What did I miss ?

**Comment by borisdayma** [comment]
Make sure you have latest version of `nbdev` (install from git)

**Comment by philtrade** [comment]
> Make sure you have latest version of `nbdev` (install from git)

Thank you.  Retrying now.

**Comment by philtrade** [comment]
after updating/installing latest `nbdev`, still getting `nbdev_diff_nbs` @ CI, even though none in local repo. Will retry from scratch.

**Pull request closed without merging**
